[16.0][IMP] account_tax_balance
OCA/account-financial-reporting pull request #1051
Opened 2023-07-12 10:31 UTC by anddago78

We have improved this module by hiding the financial type field only in the sales invoices and the purchase invoice and in the refunds

MT-2160 @moduon @rafaelbn @Shide @yajo please reviews :)

2023-07-12 11:00 UTC, Shide requested changes
Simplification

2023-07-12 11:00 UTC, Shide commented on account_tax_balance/views/account_move_view.xml
> +                    invisible="context.get('default_move_type') in ['out_invoice','in_invoice','out_refund','in_refund']"
I think it's too complicated using context on this. `move_type` field is always present on the `account.view_move_form`. Maybe simplify like this:
```suggestion
                    attrs="{'invisible': [('move_type', 'in', ['out_invoice','in_invoice','out_refund','in_refund'])]}"
```

2023-07-12 11:10 UTC, Shide approved these changes
LGTM

2023-07-12 11:11 UTC, anddago78 commented
hI @shide all comments are resolved..

2023-07-13 06:24 UTC, yajo approved these changes

2023-07-13 06:25 UTC, pedrobaeza commented
/ocabot merge minor

2023-07-13 06:28 UTC, merged