[16.0][ADD] account_move_line_pl (profit / loss)
OCA/account-financial-reporting pull request #1115
Opened 2024-02-26 16:44 UTC by norlinhenrik

This module adds "Accounting Analysis" pivot in the reporting menu.

Some fields are added/modified in account.move.line:

* account_type (store=True)
* balance_pl (to show Profit/Loss with positive income and negative expense)

2024-05-29 07:53 UTC, rousseldenis commented
Hi @norlinhenrik prefer explicit module naming than implicit one. So, suffix should be profit_loss.

2024-05-29 11:23 UTC, norlinhenrik commented
Hi @rousseldenis Thank you for your feedback! I did some more improvements. Now you are welcome to review.

2024-07-28 22:44 UTC, rvalyi requested changes
Hello @norlinhenrik thanks for contributing. It doesn't look bad, but could you please remove the mis_builder_cash_flow/static/description/index.html change from the commit?
(you can do a rebase -i, put the original index.html from the 16.0 branch, commit index.html with --amend) and do a push -f )

2024-07-31 04:17 UTC, norlinhenrik commented
Oops, how did that happen? I have removed the unwanted file now.

2025-01-05 12:17 UTC, closed without merging