[16.0][FIX] account_financial_report: Display the values of Amount cur. + Cumul cur. values in general ledger only if necessary
OCA/account-financial-reporting pull request #1232
Opened 2024-10-10 07:45 UTC by victoralmau

Display the values of _Amount cur_. + _Cumul cur._ values in general ledger only if necessary

The currency_id field of the lines is always set, so follow the same logic as in report/templates/general_ledger and show the data only if the currency is set in the account.

@Tecnativa TT51204

2024-10-10 10:55 UTC, pedrobaeza requested changes
I have created a vendor bill in other currency:

http://oca-account-financial-reporting-16-0-pr1232-ab3db6cac61e.runboat.odoo-community.org/web?debug=1#cids=1&menu_id=126&action=251&model=account.move&view_type=form&id=16

and the amount in currency is not shown:

![imagen](https://github.com/user-attachments/assets/328d2027-dc87-4e7a-9266-81a54ff83a22)

2024-10-10 11:58 UTC, victoralmau commented
Changes done. Checking, I see that in v15 it is also wrong in xlsx.

2024-10-10 17:22 UTC, pedrobaeza commented
Almost... the cumulative is summing the other amounts:

![imagen](https://github.com/user-attachments/assets/f73623f4-7426-445a-8711-8be65d7e0fba)

2024-10-11 06:33 UTC, victoralmau commented
> Almost... the cumulative is summing the other amounts:
> 
Fixed on both sides (report and xlsx)

2024-10-15 07:03 UTC, pedrobaeza approved these changes
Tested and working:

![imagen](https://github.com/user-attachments/assets/7a6dc6d4-2149-43f7-96a2-b0142170c53e)

2024-10-15 09:07 UTC, carlosdauden approved these changes
Code LGTM

2024-10-15 09:13 UTC, pedrobaeza commented
/ocabot merge minor

2024-10-15 09:17 UTC, merged