10.0 mig account tax balance sbi
OCA/account-financial-reporting pull request #250
Opened 2016-11-19 13:21 UTC by sbidoul

2017-01-11 13:59 UTC, eLBati commented
@sbidoul thanks!

Could you check the test error
```
2016-11-19 13:26:18,704 5765 ERROR openerp_test odoo.addons.account_tax_balance.tests.test_account_tax_balance: `   File "/home/travis/build/OCA/account-financial-reporting/account_tax_balance/tests/test_account_tax_balance.py", line 70, in test_tax_balance

2016-11-19 13:26:18,704 5765 ERROR openerp_test odoo.addons.account_tax_balance.tests.test_account_tax_balance: `     self.assertEquals(tax.base_balance, 100.)

2016-11-19 13:26:18,704 5765 ERROR openerp_test odoo.addons.account_tax_balance.tests.test_account_tax_balance: ` AssertionError: 0.0 != 100.0
```
?

2017-01-11 14:42 UTC, eLBati commented
Also, rebasing the branch on top of the current 10.0 should fix the runbot issue

2017-01-11 14:43 UTC, gurneyalex commented
@sbidoul rebasing on top of 10.0 should solve the runbot skipping the build.

2017-01-11 15:01 UTC, sbidoul commented
@eLBati rebased. I don't have time to dig into the failed test right now, though.

2017-01-18 16:04 UTC, eLBati commented
@sbidoul fixed with https://github.com/OCA/account-financial-reporting/pull/250/commits/b1eb23477f4d7ba320ab93302576032b6b257a87

2017-01-18 16:04 UTC, eLBati approved these changes

2017-01-18 16:05 UTC, pedrobaeza commented on account_tax_balance/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/91/9.0
Change version

2017-01-18 16:07 UTC, pedrobaeza requested changes
The menu should have another level (with an extra parent), although it seems weird, but if not, with the web_responsive module is mixed between other menus. Can you please do it?

2017-01-18 16:23 UTC, eLBati commented
@pedrobaeza thanks, done

2017-01-18 16:30 UTC, pedrobaeza approved these changes

2017-01-18 16:55 UTC, merged