[8.0][FIX] account_financial_report: Fix syntactical error
OCA/account-financial-reporting pull request #411
Opened 2018-04-13 06:45 UTC by gboros-rgbconsulting

A syntactical error was introduced during the lint improvements.

2018-04-13 07:55 UTC, pedrobaeza requested changes
Please change version number according https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#version-numbers

2018-04-13 07:55 UTC, pedrobaeza commented on account_financial_report/wizard/wizard.py
> +               data['form']['date_from'] < res[0]['date_start']:
Indent this line one level more

2018-04-13 08:12 UTC, gboros-rgbconsulting commented
Hi Pedro,

Changes done, i am not sure if you wanted me to change the version format as well or only increment it.

2018-04-13 08:14 UTC, pedrobaeza approved these changes

2018-04-13 08:14 UTC, pedrobaeza commented
Yeah, it's correct now in its full format

2018-04-17 16:06 UTC, pedrobaeza commented
Fast-tracking as trivial.

2018-04-17 16:06 UTC, merged