11.0 imp account financial reporting
OCA/account-financial-reporting pull request #444
Opened 2018-07-19 12:16 UTC by mpanarin

Allows filtering by account journal in general ledger and trial balance

2018-07-19 13:02 UTC, fclementic2c commented
@mpanarin I will not be able to test before my holidays return sorry (08/08)

2018-08-10 10:03 UTC, fclementic2c commented
perfect
thanks

2018-08-10 10:04 UTC, fclementic2c approved these changes

2018-08-10 10:06 UTC, pedrobaeza requested changes

2018-08-10 10:06 UTC, pedrobaeza commented on account_financial_report/wizard/general_ledger_wizard_view.xml
> +                    <field name="account_ids" nolabel="1" options="{'no_create': True}"/>
Why do you remove this? It's outside the scope of the PR.

2018-08-10 10:06 UTC, pedrobaeza commented on account_financial_report/wizard/trial_balance_wizard_view.xml
> +                    <field name="account_ids" nolabel="1" options="{'no_create': True}"/>
And this

2018-08-10 10:13 UTC, fclementic2c commented
@pedrobaeza It was my request (but not clearly described here)

This widget change will allow to select several accounts more easily. With the tag widget it is a real pain.
 same comment for : https://github.com/OCA/account-financial-reporting/pull/445

2018-08-10 10:17 UTC, pedrobaeza commented
I prefer not to do it. It takes a lot of space in screen. If you want to select more easily, just install https://github.com/OCA/web/tree/11.0/web_widget_many2many_tags_multi_selection

2018-08-10 10:48 UTC, yvaucher approved these changes
LGTM

Please resolve the issue raised by @pedrobaeza

2018-08-10 11:40 UTC, fclementic2c commented
@pedrobaeza ok it is a possibility.

2018-08-13 13:58 UTC, mpanarin commented
@pedrobaeza updated

2018-08-13 14:14 UTC, pedrobaeza approved these changes

2018-08-13 14:14 UTC, merged

2018-08-13 14:15 UTC, pedrobaeza commented
As a side note, for v12, we should really rid off all these SQL expressions in favor of read_group calls, that they have the same performance, but far better code maintainability and readiness.