[11.0][account_financial_report][IMP] Refactoring
OCA/account-financial-reporting pull request #484
Opened 2018-11-22 12:00 UTC by jbeficent

Changes included:
All reports:
- Rename field to hide accounts at 0 to 'hide_account_at_0'
Trial Balance:
- Add possibility to filter by hierarchy levels
- XLSX format will show the hierarchy levels in bold

General Ledger:
- Add the possibility to filter by analytic tags
- Fixes an error on the default date
Journal Ledger:
- The filter on Journals is now optional. If the user does not choose
a journal, by default it will display all journals.

Aged Partner Balance:
- Fixes an error on the default date

Hierarchy level filtering
------------------------------

With this change a user can filter what hierarchy level they want to report on.

For example, I want to show only up to level 1:
![image](https://user-images.githubusercontent.com/7683926/48901493-f089e580-ee55-11e8-9e93-d31b48eae287.png)

![image](https://user-images.githubusercontent.com/7683926/48901510-fda6d480-ee55-11e8-8510-a565caa7b9e8.png)

Now I want to show all levels:
![image](https://user-images.githubusercontent.com/7683926/48901548-14e5c200-ee56-11e8-923b-ccdd294e2d42.png)

![image](https://user-images.githubusercontent.com/7683926/48901557-1d3dfd00-ee56-11e8-8509-7cd719f867be.png)

cc @rafaelbn @pedrobaeza

2018-11-22 12:06 UTC, pedrobaeza commented
You are my idol!

2018-11-22 12:28 UTC, feketemihai commented
@jbeficent I tested on runbot and not working as expected, i think,I created 3 groups: Class 1 - > Class 10 and assigned 2 accounts to class 10, Class 2 and assigned 1 account to class 2.
Can you check if you limit to 1 or 2 levels, the result is not as expected, also we should show the accounts that under the hierarchy level, plus some layout issues,since the accounts are not added right after the hierarchy, but at the end. Also there is a layout issue in the wizard view, for Filter Accounts.

2018-11-22 12:31 UTC, feketemihai commented
@jbeficent @pedrobaeza Although , nice improvement and all others, sorry not having a lot of time to be more involved.

2018-11-22 12:37 UTC, jbeficent commented
@feketemihai I display the trial balance UP TO the level that the user chooses.
So, for example, if the user chooses to display up to level 1, it will display account groups in level 0 and level 1, but not level 2 and beyond.

2018-11-22 12:39 UTC, jbeficent commented
@feketemihai My mistake. You are right. Should only display accounts in the level you choose to show. Fixing now.

2018-11-22 12:50 UTC, jbeficent commented
@feketemihai Fixed.

2018-11-23 18:40 UTC, jbeficent commented
@jcoux can you please review this PR? It includes a forward-port to v11 of your PR https://github.com/OCA/account-financial-reporting/pull/416 to add the filters on analytic tags to the general ledger

2018-11-27 14:20 UTC, feketemihai commented
@jbeficent probably it was some misunderstanding in what i commented before, i attach how it should look like, probably much easier to check them
[Hierarchy level.pdf](https://github.com/OCA/account-financial-reporting/files/2620325/Hierarchy.level.pdf)

2018-11-27 14:29 UTC, fclementic2c commented
I am a bit surprise by this feature since you take the assumption that level are consistent through a chart of account but this is far from being the case.

Ex: A level 2 in the accounts 6... can be equivalent to a level 3 or 4 for the accounts starting by 7...  

In my view you are going a bit to far here (but this is just an opinion, I will not block the PR)

2018-11-27 15:12 UTC, jbeficent commented
@fclementic2c In Spain (and perhaps in other countries too) the levels are specific. Level 3 has a certain meaning. But since this could not be the case in other countries, this would be an optional feature.

@feketemihai I understand that you want to show all the levels above, right? I was debating with this. But then, are we talking about a Trial Balance? A Trial Balance report is supposed to total to 0 the initial and final balances. With a hierarchy this is impossible.

2018-11-28 06:21 UTC, feketemihai commented
@jbeficent I think your wrong, if you take the hierarchy plus accounts on the same level, the total will always be zero, it's just you are not showing the next levels...that's it, it's too much to work on this, and yes, it's probably much better to only show the hierarchy

2018-11-28 06:34 UTC, feketemihai approved these changes

2018-11-29 01:33 UTC, rafaelbn commented
OMG! @jbeficent great!!!! :astonished:

2018-11-29 02:59 UTC, rafaelbn commented
Tested :+1: 

But I discovered a BUG in the module in both v10 an d v11. The journal ledger now is by journals and you cannot extract the journal ledger for all the journals :astonished: Always we could have a journal ledger for all the journals. I did it in v10 and now it is nor possible.

In Spain this is a legal requirement to present the company accounting...

![journal ledger for all journals](https://user-images.githubusercontent.com/8736623/49196387-0c781480-f38b-11e8-9ec3-0c70b688d862.png)

2018-11-29 03:00 UTC, rafaelbn approved these changes
Tested functionally :+1:

2018-11-29 07:31 UTC, jcoux requested changes

2018-11-29 07:31 UTC, jcoux commented on account_financial_report/report/general_ledger.py
> +            self.id or 'NULL',
Why do you add the `or 'NULL'`?
The report_id must not is null.
We need the `report_id` to distinct each different asking of reports.

2018-11-29 10:25 UTC, JordiBForgeFlow commented
> Tested 
> 
> But I discovered a BUG in the module in both v10 an d v11. The journal ledger now is by journals and you cannot extract the journal ledger for all the journals  Always we could have a journal ledger for all the journals. I did it in v10 and now it is nor possible.
> 
> In Spain this is a legal requirement to present the company accounting...
> 
> ![journal ledger for all journals](https://user-images.githubusercontent.com/8736623/49196387-0c781480-f38b-11e8-9ec3-0c70b688d862.png)

This is now fixed.

2018-11-29 10:28 UTC, JordiBForgeFlow commented on account_financial_report/report/general_ledger.py
> +            self.id or 'NULL',
Fixed here and in https://github.com/OCA/account-financial-reporting/pull/485/commits/f9d47e5b3274bcbdc03f044b345772e4eaea8c50

2018-11-29 11:53 UTC, jbeficent commented
@feketemihai @fclementic2c I have fixed the hierarchy level filtering according to your requirements. They will also work for Spain.

Can you do a final review?

Please notice that for simplicity the first hierarchy level is 1 now.

2018-11-30 09:01 UTC, merged