[FIX] Covers the case where name and ref are strictly the same in account_move_line
OCA/account-financial-reporting pull request #601
Opened 2019-07-31 10:41 UTC by cvinh

Fixes the following use case : 
If the fields name and ref are the same in account_move_line, nothing appears in the description column of the reports

2019-10-16 03:25 UTC, gdgellatly commented
This looks wrong to me. It appears to break the case where they aren't the same, however one is in the other, and you would have both appear.

2020-01-30 18:13 UTC, MiquelRForgeFlow commented on partner_statement/views/activity_statement.xml
>                                                      <t t-if="line['ref'] not in line['name']">
```suggestion
                                                     <t t-if="line['ref'] not in line['name'] or line['ref'] == line['name']">
```
please, do this instead

2020-01-30 18:14 UTC, MiquelRForgeFlow commented
and rebase

2020-01-31 13:26 UTC, MiquelRForgeFlow commented
Superseded by https://github.com/OCA/account-financial-reporting/pull/652.

2020-01-31 13:27 UTC, MiquelRForgeFlow requested changes
Should be closed.

2023-01-01 12:13 UTC, closed without merging