[WIP][13.0] account_financial_report: migrate
OCA/account-financial-reporting pull request #620
Opened 2019-10-01 15:52 UTC by i-vyshnevska

waiting for migration of date_range, report_xlsx

2019-12-27 18:17 UTC, ernestotejeda requested changes
Add a file called oca_dependencies.txt in the repository root and put server-ux inside it so that the date_range module can be found.

You can add this too:
reporting-engine https://github.com/schout-it/reporting-engine 13.0-mig-report_xlsx
until report_xlsx is mixed and so this module can be tested

It will finally look like this:
server-ux
reporting-engine https://github.com/schout-it/reporting-engine 13.0-mig-report_xlsx

2019-12-27 18:17 UTC, ernestotejeda commented on account_financial_report/models/account_move_line.py
> +from odoo import api, models
'odoo.api' imported but unused
https://travis-ci.org/OCA/account-financial-reporting/jobs/592101257#L339

2019-12-31 13:37 UTC, bhaveshselarka commented
@i-vyshnevska Thanks for migration, its ready for use?

2019-12-31 19:49 UTC, i-vyshnevska commented
this pr is blocked by other modules migration and there already new commits it should be redone

2019-12-31 19:49 UTC, closed without merging

2020-01-08 08:24 UTC, bhaveshselarka commented
@i-vyshnevska @ernestotejeda 

https://github.com/OCA/reporting-engine/pull/331

2020-01-20 10:06 UTC, bhaveshselarka commented
@i-vyshnevska @ernestotejeda

2020-01-28 12:09 UTC, bhaveshselarka commented
@i-vyshnevska @ernestotejeda any further updates for this PR. As it's main for accounting application to have these reports.