10.0-Trial-Balance-account.group-ordering-issue
OCA/account-financial-reporting pull request #650
Opened 2020-01-16 16:56 UTC by flotho

Backport of the issue https://github.com/OCA/account-financial-reporting/pull/615 from v12.0

2020-01-16 17:27 UTC, flotho commented
@JordiBForgeFlow , please add need review tag

2020-02-05 08:35 UTC, flotho commented
Hi @pedrobaeza ,

Who am I suppose to ping here ? Jordi Balester ?

2020-02-05 16:24 UTC, pedrobaeza commented
Check who created that code.

2020-02-05 22:09 UTC, flotho commented
Hi @gaikaz , @amcor ,

Any chance to be reviewed ?

Regards

2020-02-06 07:17 UTC, gaikaz requested changes
The changes look ok in general apart from that one comma.
I could also do my little test case described in the original issue: https://github.com/OCA/account-financial-reporting/issues/609#issue-486261606 
But only later today, worst case - tomorrow.

2020-02-06 07:17 UTC, gaikaz commented on account_financial_report_qweb/report/trial_balance.py
> +    sequence = fields.Char(index=True, )
Redundant comma. Also, in v12 it has `default='1'` here. Personally can't see when would sequence not get set, but maybe still leave it?
```suggestion
    sequence = fields.Char(index=True)
```

2020-02-06 17:37 UTC, gaikaz commented
@flotho I've gone out of my way and during free time, I got Odoo v10 running and, like promised in my PR, tried to reproduce the inconsistent ordering issue the way I could reproduce it on v12.
I'm sorry to say, I couldn't :neutral_face: 
I used this module before the changes of this PR. If I would have reproduced it, then I would have tried it with the changes to see if they actually fix it. 

Could you maybe provide a step by step reproduction guide for a fresh install of Odoo v10 with/without demo data?

2020-02-09 18:09 UTC, flotho commented
Hi @gaikaz ,

Create groups in a reverse order for example :
* 700 : Revenues
* 600 : charges
* 500 : Bank
* ../...

So that before my PR the datas will be displayed in the created order and with my PR they will be ordered following group names

2020-02-20 18:00 UTC, flotho commented
ping @gaikaz , @JordiBForgeFlow

2020-03-16 16:08 UTC, gaikaz approved these changes
Sorry for the delay, @flotho 
I did a functional test now with your described scenario. It indeed is a problem and this PR fixes it.

2023-02-19 12:14 UTC, closed without merging