[13.0][FIX] partner_statement: minor fixes (partial backport)
OCA/account-financial-reporting pull request #991
Opened 2023-01-16 16:14 UTC by MiquelRForgeFlow

Backport of some minor fixes done in https://github.com/OCA/account-financial-reporting/pull/967 and https://github.com/OCA/account-financial-reporting/pull/988.

2023-02-09 04:22 UTC, gdgellatly requested changes
The PR that this is backporting seems to now produce wrong opening balances. Suggest we hold until those are resolved.

2023-02-09 12:05 UTC, MiquelRForgeFlow commented
Thanks, fixed.

2023-10-03 09:06 UTC, MiquelRForgeFlow commented
@gdgellatly I would like to merge these backport fixes. Is it fine?

2023-10-11 08:29 UTC, gdgellatly commented
@MiquelRForgeFlow I don't know, we are still stuck on a December 2022 release of partner statement because a whole load of changes landed between then and Feb and they produce wrong numbers and in some cases complete nonsense. I haven't checked since about July whether these things have been fixed, but I know the first round of fixes didn't resolve.

2025-07-21 14:33 UTC, MiquelRForgeFlow commented
Replaced by https://github.com/OCA/account-financial-reporting/pull/1179.

2025-07-21 14:33 UTC, closed without merging